### PR TITLE
Removed scrollwheel activity on map fields

### PR DESCRIPTION
**Pull request by rclachance**
Added scrollwheel: 0 to the mapOptions variable which prevents the map from scrolling on scrollwheel activity.

This can be really annoying when you're scrolling through a post edit page and you hit a map and it starts zooming like crazy. Thought this might be useful addition for others as well.

Great plugin btw!

### CODE REVIEW

**Comment by julienbechade** [comment]
Really annoying indeed but I don't want to impose it neither.

The scroll wheel UI in GM is well understood by users and I don't want to make changes that will throw people off.
But perhaps if you make it an option people could switch on and off, it might work well.

**Comment by rclachance** [comment]
Sounds like a solid plan - I'll write that up when I have a few moments - thanks!

**Comment by julienbechade** [comment]
Awesome enhancement!
Give me some time to test it first…

Thanks a lot!

**Comment by julienbechade** [comment]
@rclations Thanks again!

**Pull request merged**
