### PR TITLE
4.0 Compatability

### PR DESCRIPTION
**Pull request by fabrizim**
I modified the plugin class and file structure for compatibility with the new ACF 4.0. Thanks for the work that went into this. My patch was written a bit hastily but seems to be working - hope it helps.

### CODE REVIEW

**Comment by julienbechade** [comment]
Thanks @fabrizim!
This add-on is a mess because I made it so… I'll rewrite everything for ACF4 w/ some new features.
But thanks so much anyway for sharing your solution!

**Comment by fabrizim** [comment]
No problem - I didn't change a ton - just enough to get it to with 4.0 for
now. I actually have a separate javascript file to handle some weird
situations with using the location field inside a repeater field (google
maps can't be rendered into hidden divs without some wonkiness). Anyway -
if you want to take a look I can post it in a gist or something.

-- Mark Fabrizio Jr. Owl Watch Consulting Services, LLC Owner / Chief
Technology Officer Phone:(978) 925-9688 Fax: (978) 349-6965
http://www.owlwatch.com

**Comment by julienbechade** [comment]
I had a pick at your code through your commit…
You have an old version of the add-on. My bad, I never push an update to the WP repo.
The repeater bug is now fixed plus some enhancements.

**Comment by fabrizim** [comment]
Yeah - my bad on that - I had made changes with the code from wp plugin
download. Thanks again for the add-on - very helpful.

-- Mark Fabrizio Jr. Owl Watch Consulting Services, LLC Owner / Chief
Technology Officer Phone:(978) 925-9688 Fax: (978) 349-6965
http://www.owlwatch.com

**Pull request closed without merging**
